replicaCount: 2

autoscaling:
  enabled: false

global:
  awsAccountId: ""
  awsRegion: "us-east-1"
  image:
    registry: ""
    project: ""
    repository: ecommerce-repo

image:
  name: admin-backoffice-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.platform-observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "admin-backoffice-service"
  METABASE_SITE_URL: "http://metabase.tooling-metabase.svc.cluster.local:3000"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

serviceAccount:
  create: true

  name: admin-backoffice-service


podDisruptionBudget:
  enabled: true
